FROM openjdk:8

ARG tcpPort

ENV DOWNLOAD http://www.h2database.com/h2-2019-03-13.zip
ENV DATA_DIR /opt/h2-data
ENV TCP_PORT $tcpPort
ENV USER SA
ENV PSSWD V0cTrainer

# download h2
RUN mkdir -p ${DATA_DIR} \
    && curl ${DOWNLOAD} -o h2.zip \
    && unzip h2.zip -d /opt/ \
    && rm h2.zip

EXPOSE 81 $tcpPort
WORKDIR /opt/h2-data
# start and detach h2 db for setup
RUN java -cp /opt/h2/bin/h2*.jar org.h2.tools.Server \
 	-tcp -tcpAllowOthers -tcpPort ${TCP_PORT} \
 	-baseDir ${DATA_DIR} \
	-ifNotExists \
	&
# connect to h2-db and set password for user sa
RUN java -cp /opt/h2/bin/h2*.jar org.h2.tools.Shell \
	-url jdbc:h2:tcp://localhost:${TCP_PORT}/${DATA_DIR} \
	-driver org.h2.Driver \
	-user ${USER} \
	-sql "ALTER USER ${USER} SET PASSWORD '${PSSWD}';"
# connect to h2-db and shutdown
RUN java -cp /opt/h2/bin/h2*.jar org.h2.tools.Shell \
	-url jdbc:h2:tcp://localhost:${TCP_PORT}/${DATA_DIR} \
	-driver org.h2.Driver \
	-user ${USER} \
	-password ${PSSWD} \
	-sql "SHUTDOWN;"


CMD java -cp /opt/h2/bin/h2*.jar org.h2.tools.Server \
 	-web -webAllowOthers -webPort 81 \
 	-tcp -tcpAllowOthers -tcpPort ${TCP_PORT} \
 	-baseDir ${DATA_DIR} \
	-ifNotExists
