language: java

jdk: openjdk8

services:
   - docker

# skip installation step
install: true

cache:
   directories:
      - $HOME/.m2
      
env: DISPLAY=:99.0
before_script:
   - sh -e /etc/init.d/xvfb start

script:
   - mvn -f myProjects.vocableTrainer/pom.xml clean verify -Pcode-coverage
   #,mutation-testing
